// Generated from material-icon-theme 5.36.1 manifest — do not edit by hand.
// Regenerate with scratchpad/curate_icons.py. Keys are lowercase; tables sorted for binary search.

pub(crate) static DEFAULT_FILE: &str = "icons/file/file.svg";
pub(crate) static DEFAULT_FOLDER: &str = "icons/file/folder.svg";
pub(crate) static DEFAULT_FOLDER_OPEN: &str = "icons/file/folder-open.svg";

pub(crate) static FILE_NAMES: &[(&str, &str)] = &[
    (".buildignore", "icons/file/settings.svg"),
    (".bun-version", "icons/file/bun.svg"),
    (".clang-format", "icons/file/settings.svg"),
    (".clang-format-ignore", "icons/file/settings.svg"),
    (".clang-tidy", "icons/file/settings.svg"),
    (".conf", "icons/file/settings.svg"),
    (".dev.vars", "icons/file/tune.svg"),
    (".env.alpha", "icons/file/tune.svg"),
    (".env.defaults", "icons/file/tune.svg"),
    (".env.dev", "icons/file/tune.svg"),
    (".env.dev.local", "icons/file/tune.svg"),
    (".env.development", "icons/file/tune.svg"),
    (".env.development.local", "icons/file/tune.svg"),
    (".env.dist", "icons/file/tune.svg"),
    (".env.e2e", "icons/file/tune.svg"),
    (".env.example", "icons/file/tune.svg"),
    (".env.local", "icons/file/tune.svg"),
    (".env.preview", "icons/file/tune.svg"),
    (".env.prod", "icons/file/tune.svg"),
    (".env.prod.example", "icons/file/tune.svg"),
    (".env.prod.local", "icons/file/tune.svg"),
    (".env.production", "icons/file/tune.svg"),
    (".env.production.example", "icons/file/tune.svg"),
    (".env.production.local", "icons/file/tune.svg"),
    (".env.qa", "icons/file/tune.svg"),
    (".env.qa.local", "icons/file/tune.svg"),
    (".env.sample", "icons/file/tune.svg"),
    (".env.schema", "icons/file/tune.svg"),
    (".env.stage", "icons/file/tune.svg"),
    (".env.staging", "icons/file/tune.svg"),
    (".env.staging.local", "icons/file/tune.svg"),
    (".env.stg", "icons/file/tune.svg"),
    (".env.stg.local", "icons/file/tune.svg"),
    (".env.template", "icons/file/tune.svg"),
    (".env.test", "icons/file/tune.svg"),
    (".env.test.local", "icons/file/tune.svg"),
    (".env.testing", "icons/file/tune.svg"),
    (".env.uat", "icons/file/tune.svg"),
    (".envrc", "icons/file/console.svg"),
    (".esformatter", "icons/file/json.svg"),
    (".eslintcache", "icons/file/eslint.svg"),
    (".eslintignore", "icons/file/eslint.svg"),
    (".eslintrc", "icons/file/eslint.svg"),
    (".eslintrc-jsdoc.js", "icons/file/eslint.svg"),
    (".eslintrc-md.js", "icons/file/eslint.svg"),
    (".eslintrc.base.json", "icons/file/eslint.svg"),
    (".eslintrc.cjs", "icons/file/eslint.svg"),
    (".eslintrc.cts", "icons/file/eslint.svg"),
    (".eslintrc.js", "icons/file/eslint.svg"),
    (".eslintrc.json", "icons/file/eslint.svg"),
    (".eslintrc.json5", "icons/file/eslint.svg"),
    (".eslintrc.jsonc", "icons/file/eslint.svg"),
    (".eslintrc.mjs", "icons/file/eslint.svg"),
    (".eslintrc.mts", "icons/file/eslint.svg"),
    (".eslintrc.toml", "icons/file/eslint.svg"),
    (".eslintrc.ts", "icons/file/eslint.svg"),
    (".eslintrc.yaml", "icons/file/eslint.svg"),
    (".eslintrc.yml", "icons/file/eslint.svg"),
    (".esmrc", "icons/file/nodejs.svg"),
    (".git", "icons/file/git.svg"),
    (".git-blame-ignore", "icons/file/git.svg"),
    (".git-blame-ignore-revs", "icons/file/git.svg"),
    (".git-for-windows-updater", "icons/file/git.svg"),
    (".gitattributes", "icons/file/git.svg"),
    (".gitattributes-global", "icons/file/git.svg"),
    (".gitattributes_global", "icons/file/git.svg"),
    (".gitconfig", "icons/file/git.svg"),
    (".gitignore", "icons/file/git.svg"),
    (".gitignore-global", "icons/file/git.svg"),
    (".gitignore_global", "icons/file/git.svg"),
    (".gitinclude", "icons/file/git.svg"),
    (".gitkeep", "icons/file/git.svg"),
    (".gitmessage", "icons/file/git.svg"),
    (".gitmodules", "icons/file/git.svg"),
    (".gitpreserve", "icons/file/git.svg"),
    (".graphqlconfig", "icons/file/graphql.svg"),
    (".graphqlrc", "icons/file/graphql.svg"),
    (".graphqlrc.cjs", "icons/file/graphql.svg"),
    (".graphqlrc.cts", "icons/file/graphql.svg"),
    (".graphqlrc.js", "icons/file/graphql.svg"),
    (".graphqlrc.json", "icons/file/graphql.svg"),
    (".graphqlrc.json5", "icons/file/graphql.svg"),
    (".graphqlrc.jsonc", "icons/file/graphql.svg"),
    (".graphqlrc.mjs", "icons/file/graphql.svg"),
    (".graphqlrc.mts", "icons/file/graphql.svg"),
    (".graphqlrc.toml", "icons/file/graphql.svg"),
    (".graphqlrc.ts", "icons/file/graphql.svg"),
    (".graphqlrc.yaml", "icons/file/graphql.svg"),
    (".graphqlrc.yml", "icons/file/graphql.svg"),
    (".htaccess", "icons/file/xml.svg"),
    (".htpasswd", "icons/file/key.svg"),
    (".hushlogin", "icons/file/console.svg"),
    (".jestrc", "icons/file/jest.svg"),
    (".jestrc.js", "icons/file/jest.svg"),
    (".jestrc.json", "icons/file/jest.svg"),
    (".jsbeautifyrc", "icons/file/json.svg"),
    (".jscsrc", "icons/file/json.svg"),
    (".jshintignore", "icons/file/settings.svg"),
    (".jshintrc", "icons/file/json.svg"),
    (".keep", "icons/file/git.svg"),
    (".luacheckrc", "icons/file/lua.svg"),
    (".mailmap", "icons/file/email.svg"),
    (".mrconfig", "icons/file/settings.svg"),
    (".node-version", "icons/file/nodejs.svg"),
    (".npmignore", "icons/file/npm.svg"),
    (".npmrc", "icons/file/npm.svg"),
    (".nvmrc", "icons/file/nodejs.svg"),
    (".pnpmfile.cjs", "icons/file/pnpm.svg"),
    (".prettierignore", "icons/file/prettier.svg"),
    (".prettierrc", "icons/file/prettier.svg"),
    (".prettierrc.cjs", "icons/file/prettier.svg"),
    (".prettierrc.cts", "icons/file/prettier.svg"),
    (".prettierrc.js", "icons/file/prettier.svg"),
    (".prettierrc.json", "icons/file/prettier.svg"),
    (".prettierrc.json5", "icons/file/prettier.svg"),
    (".prettierrc.jsonc", "icons/file/prettier.svg"),
    (".prettierrc.mjs", "icons/file/prettier.svg"),
    (".prettierrc.mts", "icons/file/prettier.svg"),
    (".prettierrc.toml", "icons/file/prettier.svg"),
    (".prettierrc.ts", "icons/file/prettier.svg"),
    (".prettierrc.yaml", "icons/file/prettier.svg"),
    (".prettierrc.yml", "icons/file/prettier.svg"),
    (".pubignore", "icons/file/dart.svg"),
    (".rhistory", "icons/file/r.svg"),
    (".ruby-version", "icons/file/ruby.svg"),
    (".secrets", "icons/file/key.svg"),
    (".swift-format", "icons/file/swift.svg"),
    (".swift-version", "icons/file/swift.svg"),
    (".swiftformat", "icons/file/swift.svg"),
    (".vars", "icons/file/tune.svg"),
    (".whitesource", "icons/file/json.svg"),
    (".yardopts", "icons/file/settings.svg"),
    (".yarn-integrity", "icons/file/yarn.svg"),
    (".yarnclean", "icons/file/yarn.svg"),
    (".yarnrc", "icons/file/yarn.svg"),
    (".yarnrc.yaml", "icons/file/yarn.svg"),
    (".yarnrc.yml", "icons/file/yarn.svg"),
    ("apkbuild", "icons/file/console.svg"),
    ("appraisals", "icons/file/ruby.svg"),
    ("bashrc_apple_terminal", "icons/file/console.svg"),
    ("berksfile", "icons/file/ruby.svg"),
    ("berksfile.lock", "icons/file/ruby.svg"),
    ("brewfile", "icons/file/ruby.svg"),
    ("bun.lock", "icons/file/bun.svg"),
    ("bun.lockb", "icons/file/bun.svg"),
    ("bunfig.toml", "icons/file/bun.svg"),
    ("capfile", "icons/file/ruby.svg"),
    ("cdp.pid", "icons/file/json.svg"),
    ("changelog", "icons/file/changelog.svg"),
    ("changelog.md", "icons/file/changelog.svg"),
    ("changelog.rst", "icons/file/changelog.svg"),
    ("changelog.txt", "icons/file/changelog.svg"),
    ("changes", "icons/file/changelog.svg"),
    ("changes.md", "icons/file/changelog.svg"),
    ("changes.rst", "icons/file/changelog.svg"),
    ("changes.txt", "icons/file/changelog.svg"),
    ("cheffile", "icons/file/ruby.svg"),
    ("cmakecache.txt", "icons/file/cmake.svg"),
    ("cmakelists.txt", "icons/file/cmake.svg"),
    ("cmakepresets.json", "icons/file/cmake.svg"),
    ("commit-msg", "icons/file/console.svg"),
    ("commit_editmsg", "icons/file/git.svg"),
    ("compile_flags.txt", "icons/file/settings.svg"),
    ("compose.alpha.yaml", "icons/file/docker.svg"),
    ("compose.alpha.yml", "icons/file/docker.svg"),
    ("compose.beta.yaml", "icons/file/docker.svg"),
    ("compose.beta.yml", "icons/file/docker.svg"),
    ("compose.ci.yaml", "icons/file/docker.svg"),
    ("compose.ci.yml", "icons/file/docker.svg"),
    ("compose.dev.yaml", "icons/file/docker.svg"),
    ("compose.dev.yml", "icons/file/docker.svg"),
    ("compose.development.yaml", "icons/file/docker.svg"),
    ("compose.development.yml", "icons/file/docker.svg"),
    ("compose.local.yaml", "icons/file/docker.svg"),
    ("compose.local.yml", "icons/file/docker.svg"),
    ("compose.override.yaml", "icons/file/docker.svg"),
    ("compose.override.yml", "icons/file/docker.svg"),
    ("compose.prod.yaml", "icons/file/docker.svg"),
    ("compose.prod.yml", "icons/file/docker.svg"),
    ("compose.production.yaml", "icons/file/docker.svg"),
    ("compose.production.yml", "icons/file/docker.svg"),
    ("compose.stage.yaml", "icons/file/docker.svg"),
    ("compose.stage.yml", "icons/file/docker.svg"),
    ("compose.staging.yaml", "icons/file/docker.svg"),
    ("compose.staging.yml", "icons/file/docker.svg"),
    ("compose.test.yaml", "icons/file/docker.svg"),
    ("compose.test.yml", "icons/file/docker.svg"),
    ("compose.testing.yaml", "icons/file/docker.svg"),
    ("compose.testing.yml", "icons/file/docker.svg"),
    ("compose.web.yaml", "icons/file/docker.svg"),
    ("compose.web.yml", "icons/file/docker.svg"),
    ("compose.worker.yaml", "icons/file/docker.svg"),
    ("compose.worker.yml", "icons/file/docker.svg"),
    ("compose.yaml", "icons/file/docker.svg"),
    ("compose.yml", "icons/file/docker.svg"),
    ("composer.lock", "icons/file/json.svg"),
    ("containerfile", "icons/file/docker.svg"),
    ("containerfile.alpha", "icons/file/docker.svg"),
    ("containerfile.beta", "icons/file/docker.svg"),
    ("containerfile.ci", "icons/file/docker.svg"),
    ("containerfile.dev", "icons/file/docker.svg"),
    ("containerfile.development", "icons/file/docker.svg"),
    ("containerfile.local", "icons/file/docker.svg"),
    ("containerfile.prod", "icons/file/docker.svg"),
    ("containerfile.production", "icons/file/docker.svg"),
    ("containerfile.stage", "icons/file/docker.svg"),
    ("containerfile.staging", "icons/file/docker.svg"),
    ("containerfile.test", "icons/file/docker.svg"),
    ("containerfile.testing", "icons/file/docker.svg"),
    ("containerfile.web", "icons/file/docker.svg"),
    ("containerfile.worker", "icons/file/docker.svg"),
    ("copying", "icons/file/license.svg"),
    ("copying.md", "icons/file/license.svg"),
    ("copying.rst", "icons/file/license.svg"),
    ("copying.txt", "icons/file/license.svg"),
    ("copyright", "icons/file/license.svg"),
    ("copyright.md", "icons/file/license.svg"),
    ("copyright.rst", "icons/file/license.svg"),
    ("copyright.txt", "icons/file/license.svg"),
    ("dangerfile", "icons/file/ruby.svg"),
    ("deliverfile", "icons/file/ruby.svg"),
    ("docker-compose.alpha.yaml", "icons/file/docker.svg"),
    ("docker-compose.alpha.yml", "icons/file/docker.svg"),
    ("docker-compose.beta.yaml", "icons/file/docker.svg"),
    ("docker-compose.beta.yml", "icons/file/docker.svg"),
    ("docker-compose.ci.yaml", "icons/file/docker.svg"),
    ("docker-compose.ci.yml", "icons/file/docker.svg"),
    ("docker-compose.dev.yaml", "icons/file/docker.svg"),
    ("docker-compose.dev.yml", "icons/file/docker.svg"),
    ("docker-compose.development.yaml", "icons/file/docker.svg"),
    ("docker-compose.development.yml", "icons/file/docker.svg"),
    ("docker-compose.local.yaml", "icons/file/docker.svg"),
    ("docker-compose.local.yml", "icons/file/docker.svg"),
    ("docker-compose.override.yaml", "icons/file/docker.svg"),
    ("docker-compose.override.yml", "icons/file/docker.svg"),
    ("docker-compose.prod.yaml", "icons/file/docker.svg"),
    ("docker-compose.prod.yml", "icons/file/docker.svg"),
    ("docker-compose.production.yaml", "icons/file/docker.svg"),
    ("docker-compose.production.yml", "icons/file/docker.svg"),
    ("docker-compose.stage.yaml", "icons/file/docker.svg"),
    ("docker-compose.stage.yml", "icons/file/docker.svg"),
    ("docker-compose.staging.yaml", "icons/file/docker.svg"),
    ("docker-compose.staging.yml", "icons/file/docker.svg"),
    ("docker-compose.test.yaml", "icons/file/docker.svg"),
    ("docker-compose.test.yml", "icons/file/docker.svg"),
    ("docker-compose.testing.yaml", "icons/file/docker.svg"),
    ("docker-compose.testing.yml", "icons/file/docker.svg"),
    ("docker-compose.web.yaml", "icons/file/docker.svg"),
    ("docker-compose.web.yml", "icons/file/docker.svg"),
    ("docker-compose.worker.yaml", "icons/file/docker.svg"),
    ("docker-compose.worker.yml", "icons/file/docker.svg"),
    ("docker-compose.yaml", "icons/file/docker.svg"),
    ("docker-compose.yml", "icons/file/docker.svg"),
    ("dockerfile", "icons/file/docker.svg"),
    ("dockerfile.alpha", "icons/file/docker.svg"),
    ("dockerfile.beta", "icons/file/docker.svg"),
    ("dockerfile.ci", "icons/file/docker.svg"),
    ("dockerfile.dev", "icons/file/docker.svg"),
    ("dockerfile.development", "icons/file/docker.svg"),
    ("dockerfile.local", "icons/file/docker.svg"),
    ("dockerfile.prod", "icons/file/docker.svg"),
    ("dockerfile.production", "icons/file/docker.svg"),
    ("dockerfile.stage", "icons/file/docker.svg"),
    ("dockerfile.staging", "icons/file/docker.svg"),
    ("dockerfile.test", "icons/file/docker.svg"),
    ("dockerfile.testing", "icons/file/docker.svg"),
    ("dockerfile.web", "icons/file/docker.svg"),
    ("dockerfile.windows", "icons/file/docker.svg"),
    ("dockerfile.worker", "icons/file/docker.svg"),
    ("eslint-options.js", "icons/file/eslint.svg"),
    ("eslint.config.cjs", "icons/file/eslint.svg"),
    ("eslint.config.cts", "icons/file/eslint.svg"),
    ("eslint.config.js", "icons/file/eslint.svg"),
    ("eslint.config.json", "icons/file/eslint.svg"),
    ("eslint.config.json5", "icons/file/eslint.svg"),
    ("eslint.config.jsonc", "icons/file/eslint.svg"),
    ("eslint.config.mjs", "icons/file/eslint.svg"),
    ("eslint.config.mts", "icons/file/eslint.svg"),
    ("eslint.config.toml", "icons/file/eslint.svg"),
    ("eslint.config.ts", "icons/file/eslint.svg"),
    ("eslint.config.yaml", "icons/file/eslint.svg"),
    ("eslint.config.yml", "icons/file/eslint.svg"),
    ("favicon.ico", "icons/file/favicon.svg"),
    ("git-history", "icons/file/git.svg"),
    ("git-rebase-todo", "icons/file/git.svg"),
    ("gnumakefile", "icons/file/makefile.svg"),
    ("go.mod", "icons/file/go-mod.svg"),
    ("go.sum", "icons/file/go-mod.svg"),
    ("go.work", "icons/file/go-mod.svg"),
    ("go.work.sum", "icons/file/go-mod.svg"),
    ("gradle-wrapper.properties", "icons/file/gradle.svg"),
    ("gradle.properties", "icons/file/gradle.svg"),
    ("gradlew", "icons/file/gradle.svg"),
    ("gradlew.bat", "icons/file/gradle.svg"),
    ("graphql.config.cjs", "icons/file/graphql.svg"),
    ("graphql.config.cts", "icons/file/graphql.svg"),
    ("graphql.config.js", "icons/file/graphql.svg"),
    ("graphql.config.json", "icons/file/graphql.svg"),
    ("graphql.config.json5", "icons/file/graphql.svg"),
    ("graphql.config.jsonc", "icons/file/graphql.svg"),
    ("graphql.config.mjs", "icons/file/graphql.svg"),
    ("graphql.config.mts", "icons/file/graphql.svg"),
    ("graphql.config.toml", "icons/file/graphql.svg"),
    ("graphql.config.ts", "icons/file/graphql.svg"),
    ("graphql.config.yaml", "icons/file/graphql.svg"),
    ("graphql.config.yml", "icons/file/graphql.svg"),
    ("guardfile", "icons/file/ruby.svg"),
    ("gymfile", "icons/file/ruby.svg"),
    ("hobofile", "icons/file/ruby.svg"),
    ("jakefile", "icons/file/javascript.svg"),
    ("jest-e2e.config.cjs", "icons/file/jest.svg"),
    ("jest-e2e.config.cts", "icons/file/jest.svg"),
    ("jest-e2e.config.js", "icons/file/jest.svg"),
    ("jest-e2e.config.json", "icons/file/jest.svg"),
    ("jest-e2e.config.mjs", "icons/file/jest.svg"),
    ("jest-e2e.config.mts", "icons/file/jest.svg"),
    ("jest-e2e.config.ts", "icons/file/jest.svg"),
    ("jest-e2e.json", "icons/file/jest.svg"),
    ("jest-github-actions-reporter.js", "icons/file/jest.svg"),
    ("jest-preset.cjs", "icons/file/jest.svg"),
    ("jest-preset.js", "icons/file/jest.svg"),
    ("jest-preset.json", "icons/file/jest.svg"),
    ("jest-preset.mjs", "icons/file/jest.svg"),
    ("jest-unit.config.js", "icons/file/jest.svg"),
    ("jest.config.cjs", "icons/file/jest.svg"),
    ("jest.config.cts", "icons/file/jest.svg"),
    ("jest.config.js", "icons/file/jest.svg"),
    ("jest.config.json", "icons/file/jest.svg"),
    ("jest.config.mjs", "icons/file/jest.svg"),
    ("jest.config.mts", "icons/file/jest.svg"),
    ("jest.config.ts", "icons/file/jest.svg"),
    ("jest.e2e.config.cjs", "icons/file/jest.svg"),
    ("jest.e2e.config.cts", "icons/file/jest.svg"),
    ("jest.e2e.config.js", "icons/file/jest.svg"),
    ("jest.e2e.config.json", "icons/file/jest.svg"),
    ("jest.e2e.config.mjs", "icons/file/jest.svg"),
    ("jest.e2e.config.mts", "icons/file/jest.svg"),
    ("jest.e2e.config.ts", "icons/file/jest.svg"),
    ("jest.e2e.json", "icons/file/jest.svg"),
    ("jest.json", "icons/file/jest.svg"),
    ("jest.preset.cjs", "icons/file/jest.svg"),
    ("jest.preset.js", "icons/file/jest.svg"),
    ("jest.preset.json", "icons/file/jest.svg"),
    ("jest.preset.mjs", "icons/file/jest.svg"),
    ("jest.setup.js", "icons/file/jest.svg"),
    ("jest.setup.ts", "icons/file/jest.svg"),
    ("jest.teardown.js", "icons/file/jest.svg"),
    ("kbuild", "icons/file/makefile.svg"),
    ("licence", "icons/file/license.svg"),
    ("licence-agpl", "icons/file/license.svg"),
    ("licence-apache", "icons/file/license.svg"),
    ("licence-bsd", "icons/file/license.svg"),
    ("licence-gpl", "icons/file/license.svg"),
    ("licence-lgpl", "icons/file/license.svg"),
    ("licence-mit", "icons/file/license.svg"),
    ("licence.md", "icons/file/license.svg"),
    ("licence.rst", "icons/file/license.svg"),
    ("licence.txt", "icons/file/license.svg"),
    ("license", "icons/file/license.svg"),
    ("license-agpl", "icons/file/license.svg"),
    ("license-apache", "icons/file/license.svg"),
    ("license-bsd", "icons/file/license.svg"),
    ("license-gpl", "icons/file/license.svg"),
    ("license-lgpl", "icons/file/license.svg"),
    ("license-mit", "icons/file/license.svg"),
    ("license.md", "icons/file/license.svg"),
    ("license.rst", "icons/file/license.svg"),
    ("license.txt", "icons/file/license.svg"),
    ("makefile", "icons/file/makefile.svg"),
    ("manifest.mf", "icons/file/settings.svg"),
    ("matchfile", "icons/file/ruby.svg"),
    ("merge_msg", "icons/file/git.svg"),
    ("package-lock.json", "icons/file/nodejs.svg"),
    ("package.json", "icons/file/nodejs.svg"),
    ("pkgbuild", "icons/file/console.svg"),
    ("pnpm-lock.yaml", "icons/file/pnpm.svg"),
    ("pnpm-workspace.yaml", "icons/file/pnpm.svg"),
    ("podfile", "icons/file/ruby.svg"),
    ("post-merge", "icons/file/console.svg"),
    ("pre-commit", "icons/file/console.svg"),
    ("pre-push", "icons/file/console.svg"),
    ("prettier.config.cjs", "icons/file/prettier.svg"),
    ("prettier.config.cts", "icons/file/prettier.svg"),
    ("prettier.config.js", "icons/file/prettier.svg"),
    ("prettier.config.json", "icons/file/prettier.svg"),
    ("prettier.config.json5", "icons/file/prettier.svg"),
    ("prettier.config.jsonc", "icons/file/prettier.svg"),
    ("prettier.config.mjs", "icons/file/prettier.svg"),
    ("prettier.config.mts", "icons/file/prettier.svg"),
    ("prettier.config.toml", "icons/file/prettier.svg"),
    ("prettier.config.ts", "icons/file/prettier.svg"),
    ("prettier.config.yaml", "icons/file/prettier.svg"),
    ("prettier.config.yml", "icons/file/prettier.svg"),
    ("puppetfile", "icons/file/ruby.svg"),
    ("rakefile", "icons/file/ruby.svg"),
    ("rantfile", "icons/file/ruby.svg"),
    ("readme", "icons/file/readme.svg"),
    ("readme.md", "icons/file/readme.svg"),
    ("readme.rst", "icons/file/readme.svg"),
    ("readme.txt", "icons/file/readme.svg"),
    ("scanfile", "icons/file/ruby.svg"),
    ("security", "icons/file/lock.svg"),
    ("security.md", "icons/file/lock.svg"),
    ("security.txt", "icons/file/lock.svg"),
    ("sha256sums", "icons/file/key.svg"),
    ("snapfile", "icons/file/ruby.svg"),
    ("svelte.config.cjs", "icons/file/svelte.svg"),
    ("svelte.config.cts", "icons/file/svelte.svg"),
    ("svelte.config.js", "icons/file/svelte.svg"),
    ("svelte.config.mjs", "icons/file/svelte.svg"),
    ("svelte.config.mts", "icons/file/svelte.svg"),
    ("svelte.config.ts", "icons/file/svelte.svg"),
    ("tailwind.config.cjs", "icons/file/tailwindcss.svg"),
    ("tailwind.config.cts", "icons/file/tailwindcss.svg"),
    ("tailwind.config.js", "icons/file/tailwindcss.svg"),
    ("tailwind.config.mjs", "icons/file/tailwindcss.svg"),
    ("tailwind.config.mts", "icons/file/tailwindcss.svg"),
    ("tailwind.config.ts", "icons/file/tailwindcss.svg"),
    ("tailwind.js", "icons/file/tailwindcss.svg"),
    ("tailwind.ts", "icons/file/tailwindcss.svg"),
    ("thorfile", "icons/file/ruby.svg"),
    ("todo.md", "icons/file/todo.svg"),
    ("todos.md", "icons/file/todo.svg"),
    ("vite.config.cjs", "icons/file/vite.svg"),
    ("vite.config.cts", "icons/file/vite.svg"),
    ("vite.config.js", "icons/file/vite.svg"),
    ("vite.config.mjs", "icons/file/vite.svg"),
    ("vite.config.mts", "icons/file/vite.svg"),
    ("vite.config.ts", "icons/file/vite.svg"),
    ("vitest.config.cjs", "icons/file/vitest.svg"),
    ("vitest.config.cts", "icons/file/vitest.svg"),
    ("vitest.config.js", "icons/file/vitest.svg"),
    ("vitest.config.mjs", "icons/file/vitest.svg"),
    ("vitest.config.mts", "icons/file/vitest.svg"),
    ("vitest.config.ts", "icons/file/vitest.svg"),
    ("vitest.e2e.config.cjs", "icons/file/vitest.svg"),
    ("vitest.e2e.config.cts", "icons/file/vitest.svg"),
    ("vitest.e2e.config.js", "icons/file/vitest.svg"),
    ("vitest.e2e.config.mjs", "icons/file/vitest.svg"),
    ("vitest.e2e.config.mts", "icons/file/vitest.svg"),
    ("vitest.e2e.config.ts", "icons/file/vitest.svg"),
    ("vitest.unit.config.cjs", "icons/file/vitest.svg"),
    ("vitest.unit.config.cts", "icons/file/vitest.svg"),
    ("vitest.unit.config.js", "icons/file/vitest.svg"),
    ("vitest.unit.config.mjs", "icons/file/vitest.svg"),
    ("vitest.unit.config.mts", "icons/file/vitest.svg"),
    ("vitest.unit.config.ts", "icons/file/vitest.svg"),
    ("vitest.workspace.cjs", "icons/file/vitest.svg"),
    ("vitest.workspace.cts", "icons/file/vitest.svg"),
    ("vitest.workspace.js", "icons/file/vitest.svg"),
    ("vitest.workspace.mjs", "icons/file/vitest.svg"),
    ("vitest.workspace.mts", "icons/file/vitest.svg"),
    ("vitest.workspace.ts", "icons/file/vitest.svg"),
    ("webpack.base.cjs", "icons/file/webpack.svg"),
    ("webpack.base.cts", "icons/file/webpack.svg"),
    ("webpack.base.js", "icons/file/webpack.svg"),
    ("webpack.base.mjs", "icons/file/webpack.svg"),
    ("webpack.base.mts", "icons/file/webpack.svg"),
    ("webpack.base.ts", "icons/file/webpack.svg"),
    ("webpack.cjs", "icons/file/webpack.svg"),
    ("webpack.client.cjs", "icons/file/webpack.svg"),
    ("webpack.client.cts", "icons/file/webpack.svg"),
    ("webpack.client.js", "icons/file/webpack.svg"),
    ("webpack.client.mjs", "icons/file/webpack.svg"),
    ("webpack.client.mts", "icons/file/webpack.svg"),
    ("webpack.client.ts", "icons/file/webpack.svg"),
    ("webpack.common.cjs", "icons/file/webpack.svg"),
    ("webpack.common.cts", "icons/file/webpack.svg"),
    ("webpack.common.js", "icons/file/webpack.svg"),
    ("webpack.common.mjs", "icons/file/webpack.svg"),
    ("webpack.common.mts", "icons/file/webpack.svg"),
    ("webpack.common.ts", "icons/file/webpack.svg"),
    ("webpack.config.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.base.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.base.cjs", "icons/file/webpack.svg"),
    ("webpack.config.base.cts", "icons/file/webpack.svg"),
    ("webpack.config.base.js", "icons/file/webpack.svg"),
    ("webpack.config.base.mjs", "icons/file/webpack.svg"),
    ("webpack.config.base.mts", "icons/file/webpack.svg"),
    ("webpack.config.base.ts", "icons/file/webpack.svg"),
    ("webpack.config.cjs", "icons/file/webpack.svg"),
    ("webpack.config.client.cjs", "icons/file/webpack.svg"),
    ("webpack.config.client.cts", "icons/file/webpack.svg"),
    ("webpack.config.client.js", "icons/file/webpack.svg"),
    ("webpack.config.client.mjs", "icons/file/webpack.svg"),
    ("webpack.config.client.mts", "icons/file/webpack.svg"),
    ("webpack.config.client.ts", "icons/file/webpack.svg"),
    ("webpack.config.coffee", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.common.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.common.cjs", "icons/file/webpack.svg"),
    ("webpack.config.common.cts", "icons/file/webpack.svg"),
    ("webpack.config.common.js", "icons/file/webpack.svg"),
    ("webpack.config.common.mjs", "icons/file/webpack.svg"),
    ("webpack.config.common.mts", "icons/file/webpack.svg"),
    ("webpack.config.common.ts", "icons/file/webpack.svg"),
    ("webpack.config.cts", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.dev.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.dev.cjs", "icons/file/webpack.svg"),
    ("webpack.config.dev.cts", "icons/file/webpack.svg"),
    ("webpack.config.dev.js", "icons/file/webpack.svg"),
    ("webpack.config.dev.mjs", "icons/file/webpack.svg"),
    ("webpack.config.dev.mts", "icons/file/webpack.svg"),
    ("webpack.config.dev.ts", "icons/file/webpack.svg"),
    ("webpack.config.js", "icons/file/webpack.svg"),
    ("webpack.config.main.cjs", "icons/file/webpack.svg"),
    ("webpack.config.main.cts", "icons/file/webpack.svg"),
    ("webpack.config.main.js", "icons/file/webpack.svg"),
    ("webpack.config.main.mjs", "icons/file/webpack.svg"),
    ("webpack.config.main.mts", "icons/file/webpack.svg"),
    ("webpack.config.main.ts", "icons/file/webpack.svg"),
    ("webpack.config.mjs", "icons/file/webpack.svg"),
    ("webpack.config.mts", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.prod.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.prod.cjs", "icons/file/webpack.svg"),
    ("webpack.config.prod.cts", "icons/file/webpack.svg"),
    ("webpack.config.prod.js", "icons/file/webpack.svg"),
    ("webpack.config.prod.mjs", "icons/file/webpack.svg"),
    ("webpack.config.prod.mts", "icons/file/webpack.svg"),
    ("webpack.config.prod.ts", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.production.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.production.cjs", "icons/file/webpack.svg"),
    ("webpack.config.production.cts", "icons/file/webpack.svg"),
    ("webpack.config.production.js", "icons/file/webpack.svg"),
    ("webpack.config.production.mjs", "icons/file/webpack.svg"),
    ("webpack.config.production.mts", "icons/file/webpack.svg"),
    ("webpack.config.production.ts", "icons/file/webpack.svg"),
    ("webpack.config.renderer.cjs", "icons/file/webpack.svg"),
    ("webpack.config.renderer.cts", "icons/file/webpack.svg"),
    ("webpack.config.renderer.js", "icons/file/webpack.svg"),
    ("webpack.config.renderer.mjs", "icons/file/webpack.svg"),
    ("webpack.config.renderer.mts", "icons/file/webpack.svg"),
    ("webpack.config.renderer.ts", "icons/file/webpack.svg"),
    ("webpack.config.server.cjs", "icons/file/webpack.svg"),
    ("webpack.config.server.cts", "icons/file/webpack.svg"),
    ("webpack.config.server.js", "icons/file/webpack.svg"),
    ("webpack.config.server.mjs", "icons/file/webpack.svg"),
    ("webpack.config.server.mts", "icons/file/webpack.svg"),
    ("webpack.config.server.ts", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.cjs", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.cts", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.js", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.mjs", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.mts", "icons/file/webpack.svg"),
    ("webpack.config.staging.babel.ts", "icons/file/webpack.svg"),
    ("webpack.config.staging.cjs", "icons/file/webpack.svg"),
    ("webpack.config.staging.cts", "icons/file/webpack.svg"),
    ("webpack.config.staging.js", "icons/file/webpack.svg"),
    ("webpack.config.staging.mjs", "icons/file/webpack.svg"),
    ("webpack.config.staging.mts", "icons/file/webpack.svg"),
    ("webpack.config.staging.ts", "icons/file/webpack.svg"),
    ("webpack.config.test.cjs", "icons/file/webpack.svg"),
    ("webpack.config.test.cts", "icons/file/webpack.svg"),
    ("webpack.config.test.js", "icons/file/webpack.svg"),
    ("webpack.config.test.mjs", "icons/file/webpack.svg"),
    ("webpack.config.test.mts", "icons/file/webpack.svg"),
    ("webpack.config.test.ts", "icons/file/webpack.svg"),
    ("webpack.config.ts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.cjs", "icons/file/webpack.svg"),
    ("webpack.config.vendor.cts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.js", "icons/file/webpack.svg"),
    ("webpack.config.vendor.mjs", "icons/file/webpack.svg"),
    ("webpack.config.vendor.mts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.cjs", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.cts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.js", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.mjs", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.mts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.production.ts", "icons/file/webpack.svg"),
    ("webpack.config.vendor.ts", "icons/file/webpack.svg"),
    ("webpack.cts", "icons/file/webpack.svg"),
    ("webpack.dev.cjs", "icons/file/webpack.svg"),
    ("webpack.dev.cts", "icons/file/webpack.svg"),
    ("webpack.dev.js", "icons/file/webpack.svg"),
    ("webpack.dev.mjs", "icons/file/webpack.svg"),
    ("webpack.dev.mts", "icons/file/webpack.svg"),
    ("webpack.dev.ts", "icons/file/webpack.svg"),
    ("webpack.development.cjs", "icons/file/webpack.svg"),
    ("webpack.development.cts", "icons/file/webpack.svg"),
    ("webpack.development.js", "icons/file/webpack.svg"),
    ("webpack.development.mjs", "icons/file/webpack.svg"),
    ("webpack.development.mts", "icons/file/webpack.svg"),
    ("webpack.development.ts", "icons/file/webpack.svg"),
    ("webpack.dist.cjs", "icons/file/webpack.svg"),
    ("webpack.dist.cts", "icons/file/webpack.svg"),
    ("webpack.dist.js", "icons/file/webpack.svg"),
    ("webpack.dist.mjs", "icons/file/webpack.svg"),
    ("webpack.dist.mts", "icons/file/webpack.svg"),
    ("webpack.dist.ts", "icons/file/webpack.svg"),
    ("webpack.js", "icons/file/webpack.svg"),
    ("webpack.mix.cjs", "icons/file/webpack.svg"),
    ("webpack.mix.cts", "icons/file/webpack.svg"),
    ("webpack.mix.js", "icons/file/webpack.svg"),
    ("webpack.mix.mjs", "icons/file/webpack.svg"),
    ("webpack.mix.mts", "icons/file/webpack.svg"),
    ("webpack.mix.ts", "icons/file/webpack.svg"),
    ("webpack.mjs", "icons/file/webpack.svg"),
    ("webpack.mts", "icons/file/webpack.svg"),
    ("webpack.prod.cjs", "icons/file/webpack.svg"),
    ("webpack.prod.config.cjs", "icons/file/webpack.svg"),
    ("webpack.prod.config.cts", "icons/file/webpack.svg"),
    ("webpack.prod.config.js", "icons/file/webpack.svg"),
    ("webpack.prod.config.mjs", "icons/file/webpack.svg"),
    ("webpack.prod.config.mts", "icons/file/webpack.svg"),
    ("webpack.prod.config.ts", "icons/file/webpack.svg"),
    ("webpack.prod.cts", "icons/file/webpack.svg"),
    ("webpack.prod.js", "icons/file/webpack.svg"),
    ("webpack.prod.mjs", "icons/file/webpack.svg"),
    ("webpack.prod.mts", "icons/file/webpack.svg"),
    ("webpack.prod.ts", "icons/file/webpack.svg"),
    ("webpack.production.cjs", "icons/file/webpack.svg"),
    ("webpack.production.cts", "icons/file/webpack.svg"),
    ("webpack.production.js", "icons/file/webpack.svg"),
    ("webpack.production.mjs", "icons/file/webpack.svg"),
    ("webpack.production.mts", "icons/file/webpack.svg"),
    ("webpack.production.ts", "icons/file/webpack.svg"),
    ("webpack.server.cjs", "icons/file/webpack.svg"),
    ("webpack.server.cts", "icons/file/webpack.svg"),
    ("webpack.server.js", "icons/file/webpack.svg"),
    ("webpack.server.mjs", "icons/file/webpack.svg"),
    ("webpack.server.mts", "icons/file/webpack.svg"),
    ("webpack.server.ts", "icons/file/webpack.svg"),
    ("webpack.test.cjs", "icons/file/webpack.svg"),
    ("webpack.test.cts", "icons/file/webpack.svg"),
    ("webpack.test.js", "icons/file/webpack.svg"),
    ("webpack.test.mjs", "icons/file/webpack.svg"),
    ("webpack.test.mts", "icons/file/webpack.svg"),
    ("webpack.test.ts", "icons/file/webpack.svg"),
    ("webpack.ts", "icons/file/webpack.svg"),
    ("webpackfile.cjs", "icons/file/webpack.svg"),
    ("webpackfile.cts", "icons/file/webpack.svg"),
    ("webpackfile.js", "icons/file/webpack.svg"),
    ("webpackfile.mjs", "icons/file/webpack.svg"),
    ("webpackfile.mts", "icons/file/webpack.svg"),
    ("webpackfile.ts", "icons/file/webpack.svg"),
    ("yarn-error.log", "icons/file/yarn.svg"),
    ("yarn.lock", "icons/file/yarn.svg"),
    ("zlogin", "icons/file/console.svg"),
    ("zlogout", "icons/file/console.svg"),
    ("zprofile", "icons/file/console.svg"),
    ("zshenv", "icons/file/console.svg"),
    ("zshrc", "icons/file/console.svg"),
    ("zshrc_apple_terminal", "icons/file/console.svg"),
];

pub(crate) static FILE_EXTENSIONS: &[(&str, &str)] = &[
    ("001", "icons/file/zip.svg"),
    ("3fr", "icons/file/image.svg"),
    ("7z", "icons/file/zip.svg"),
    ("8svx", "icons/file/audio.svg"),
    ("aa", "icons/file/audio.svg"),
    ("aac", "icons/file/audio.svg"),
    ("aax", "icons/file/audio.svg"),
    ("ac3", "icons/file/audio.svg"),
    ("accdb", "icons/file/database.svg"),
    ("accde", "icons/file/database.svg"),
    ("adp", "icons/file/database.svg"),
    ("afphoto", "icons/file/image.svg"),
    ("aif", "icons/file/audio.svg"),
    ("aiff", "icons/file/audio.svg"),
    ("alac", "icons/file/audio.svg"),
    ("ami", "icons/file/image.svg"),
    ("amr", "icons/file/audio.svg"),
    ("ape", "icons/file/audio.svg"),
    ("apfs", "icons/file/zip.svg"),
    ("apx", "icons/file/image.svg"),
    ("ari", "icons/file/image.svg"),
    ("arj", "icons/file/zip.svg"),
    ("arw", "icons/file/image.svg"),
    ("asc", "icons/file/key.svg"),
    ("ascx", "icons/file/xml.svg"),
    ("ase", "icons/file/image.svg"),
    ("aseprite", "icons/file/image.svg"),
    ("asp", "icons/file/html.svg"),
    ("aspx", "icons/file/html.svg"),
    ("atom", "icons/file/xml.svg"),
    ("avi", "icons/file/video.svg"),
    ("avif", "icons/file/image.svg"),
    ("awk", "icons/file/console.svg"),
    ("axaml", "icons/file/xml.svg"),
    ("axml", "icons/file/xml.svg"),
    ("bak", "icons/file/database.svg"),
    ("bash", "icons/file/console.svg"),
    ("bash_aliases", "icons/file/console.svg"),
    ("bash_login", "icons/file/console.svg"),
    ("bash_logout", "icons/file/console.svg"),
    ("bash_profile", "icons/file/console.svg"),
    ("bashrc", "icons/file/console.svg"),
    ("bat", "icons/file/console.svg"),
    ("bay", "icons/file/image.svg"),
    ("bdb", "icons/file/database.svg"),
    ("bmap", "icons/file/font.svg"),
    ("bmp", "icons/file/image.svg"),
    ("bpg", "icons/file/image.svg"),
    ("bpmn", "icons/file/xml.svg"),
    ("br", "icons/file/zip.svg"),
    ("braw", "icons/file/image.svg"),
    ("brk", "icons/file/image.svg"),
    ("brotli", "icons/file/zip.svg"),
    ("bz2", "icons/file/zip.svg"),
    ("bzip2", "icons/file/zip.svg"),
    ("c", "icons/file/c.svg"),
    ("c++", "icons/file/cpp.svg"),
    ("c++m", "icons/file/cpp.svg"),
    ("cab", "icons/file/zip.svg"),
    ("caf", "icons/file/audio.svg"),
    ("cap", "icons/file/image.svg"),
    ("cc", "icons/file/cpp.svg"),
    ("ccm", "icons/file/cpp.svg"),
    ("cda", "icons/file/audio.svg"),
    ("cdr", "icons/file/audio.svg"),
    ("cer", "icons/file/certificate.svg"),
    ("cert", "icons/file/certificate.svg"),
    ("cff", "icons/file/yaml.svg"),
    ("cfg", "icons/file/settings.svg"),
    ("cjs", "icons/file/javascript.svg"),
    ("clip", "icons/file/image.svg"),
    ("cmake", "icons/file/cmake.svg"),
    ("cmd", "icons/file/console.svg"),
    ("cnf", "icons/file/settings.svg"),
    ("compose.yaml", "icons/file/docker.svg"),
    ("compose.yml", "icons/file/docker.svg"),
    ("conf", "icons/file/settings.svg"),
    ("config", "icons/file/settings.svg"),
    ("containerfile", "icons/file/docker.svg"),
    ("containerignore", "icons/file/docker.svg"),
    ("copilotmd", "icons/file/markdown.svg"),
    ("cp", "icons/file/cpp.svg"),
    ("cpio", "icons/file/zip.svg"),
    ("cpp", "icons/file/cpp.svg"),
    ("cppm", "icons/file/cpp.svg"),
    ("cpt", "icons/file/image.svg"),
    ("cpy", "icons/file/python.svg"),
    ("cr2", "icons/file/image.svg"),
    ("cr3", "icons/file/image.svg"),
    ("crt", "icons/file/certificate.svg"),
    ("crw", "icons/file/image.svg"),
    ("cs", "icons/file/csharp.svg"),
    ("csh", "icons/file/console.svg"),
    ("csharp", "icons/file/csharp.svg"),
    ("cshrc", "icons/file/console.svg"),
    ("csl", "icons/file/xml.svg"),
    ("csproj.user", "icons/file/xml.svg"),
    ("css", "icons/file/css.svg"),
    ("csv", "icons/file/table.svg"),
    ("csx", "icons/file/csharp.svg"),
    ("ctp", "icons/file/php.svg"),
    ("cts", "icons/file/typescript.svg"),
    ("cur", "icons/file/image.svg"),
    ("cxx", "icons/file/cpp.svg"),
    ("cxxm", "icons/file/cpp.svg"),
    ("d.cts", "icons/file/typescript-def.svg"),
    ("d.ets", "icons/file/typescript-def.svg"),
    ("d.mts", "icons/file/typescript-def.svg"),
    ("d.ts", "icons/file/typescript-def.svg"),
    ("dart", "icons/file/dart.svg"),
    ("data", "icons/file/image.svg"),
    ("db", "icons/file/database.svg"),
    ("db3", "icons/file/database.svg"),
    ("dbf", "icons/file/database.svg"),
    ("dblite", "icons/file/database.svg"),
    ("dblite3", "icons/file/database.svg"),
    ("dcr", "icons/file/image.svg"),
    ("dcs", "icons/file/image.svg"),
    ("dds", "icons/file/image.svg"),
    ("deb", "icons/file/zip.svg"),
    ("debugsymbols", "icons/file/database.svg"),
    ("directory", "icons/file/settings.svg"),
    ("dita", "icons/file/xml.svg"),
    ("ditamap", "icons/file/xml.svg"),
    ("dlc", "icons/file/settings.svg"),
    ("dmn", "icons/file/xml.svg"),
    ("dng", "icons/file/image.svg"),
    ("docker-compose.yaml", "icons/file/docker.svg"),
    ("docker-compose.yml", "icons/file/docker.svg"),
    ("dockerfile", "icons/file/docker.svg"),
    ("dockerignore", "icons/file/docker.svg"),
    ("drf", "icons/file/image.svg"),
    ("dsql", "icons/file/database.svg"),
    ("dss", "icons/file/audio.svg"),
    ("dtd", "icons/file/xml.svg"),
    ("dtml", "icons/file/xml.svg"),
    ("ebuild", "icons/file/console.svg"),
    ("ec3", "icons/file/audio.svg"),
    ("eclass", "icons/file/console.svg"),
    ("edb", "icons/file/email.svg"),
    ("eex", "icons/file/elixir.svg"),
    ("efs", "icons/file/audio.svg"),
    ("eip", "icons/file/image.svg"),
    ("eml", "icons/file/email.svg"),
    ("emlx", "icons/file/email.svg"),
    ("enc", "icons/file/audio.svg"),
    ("ent", "icons/file/xml.svg"),
    ("env", "icons/file/tune.svg"),
    ("eot", "icons/file/font.svg"),
    ("eps", "icons/file/image.svg"),
    ("erb", "icons/file/ruby.svg"),
    ("erf", "icons/file/image.svg"),
    ("es6", "icons/file/javascript.svg"),
    ("esd", "icons/file/zip.svg"),
    ("esx", "icons/file/javascript.svg"),
    ("ex", "icons/file/elixir.svg"),
    ("exe", "icons/file/exe.svg"),
    ("exp", "icons/file/console.svg"),
    ("exr", "icons/file/image.svg"),
    ("exs", "icons/file/elixir.svg"),
    ("eyaml", "icons/file/yaml.svg"),
    ("eyml", "icons/file/yaml.svg"),
    ("far", "icons/file/zip.svg"),
    ("fat", "icons/file/zip.svg"),
    ("fdb", "icons/file/database.svg"),
    ("feather", "icons/file/database.svg"),
    ("fff", "icons/file/image.svg"),
    ("fish", "icons/file/console.svg"),
    ("flac", "icons/file/audio.svg"),
    ("flp", "icons/file/audio.svg"),
    ("flv", "icons/file/video.svg"),
    ("fnt", "icons/file/font.svg"),
    ("font", "icons/file/font.svg"),
    ("fonts", "icons/file/font.svg"),
    ("fpx", "icons/file/image.svg"),
    ("frm", "icons/file/database.svg"),
    ("fs", "icons/file/fsharp.svg"),
    ("fsi", "icons/file/fsharp.svg"),
    ("fsproj", "icons/file/fsharp.svg"),
    ("fsscript", "icons/file/fsharp.svg"),
    ("fsx", "icons/file/fsharp.svg"),
    ("fxml", "icons/file/xml.svg"),
    ("gbr", "icons/file/image.svg"),
    ("gdb", "icons/file/database.svg"),
    ("gemspec", "icons/file/ruby.svg"),
    ("geojson", "icons/file/json.svg"),
    ("gif", "icons/file/image.svg"),
    ("gifv", "icons/file/video.svg"),
    ("go", "icons/file/go.svg"),
    ("gp", "icons/file/audio.svg"),
    ("gpg", "icons/file/key.svg"),
    ("gpr", "icons/file/image.svg"),
    ("gql", "icons/file/graphql.svg"),
    ("gradle", "icons/file/gradle.svg"),
    ("graphql", "icons/file/graphql.svg"),
    ("gsm", "icons/file/audio.svg"),
    ("gyp", "icons/file/python.svg"),
    ("gypi", "icons/file/python.svg"),
    ("gz", "icons/file/zip.svg"),
    ("gzip", "icons/file/zip.svg"),
    ("h", "icons/file/h.svg"),
    ("h++", "icons/file/hpp.svg"),
    ("h.in", "icons/file/cpp.svg"),
    ("har", "icons/file/json.svg"),
    ("heex", "icons/file/elixir.svg"),
    ("heic", "icons/file/image.svg"),
    ("heif", "icons/file/image.svg"),
    ("hfs", "icons/file/zip.svg"),
    ("hh", "icons/file/hpp.svg"),
    ("hp", "icons/file/hpp.svg"),
    ("hpp", "icons/file/hpp.svg"),
    ("hpp.in", "icons/file/cpp.svg"),
    ("hs", "icons/file/haskell.svg"),
    ("htm", "icons/file/html.svg"),
    ("html", "icons/file/html.svg"),
    ("html_vm", "icons/file/html.svg"),
    ("hxx", "icons/file/hpp.svg"),
    ("i", "icons/file/c.svg"),
    ("ibd", "icons/file/database.svg"),
    ("icns", "icons/file/image.svg"),
    ("ico", "icons/file/image.svg"),
    ("ics", "icons/file/email.svg"),
    ("ii", "icons/file/cpp.svg"),
    ("iiq", "icons/file/image.svg"),
    ("img", "icons/file/image.svg"),
    ("iml", "icons/file/xml.svg"),
    ("ini", "icons/file/settings.svg"),
    ("inl", "icons/file/hpp.svg"),
    ("ipp", "icons/file/cpp.svg"),
    ("ipy", "icons/file/python.svg"),
    ("isml", "icons/file/xml.svg"),
    ("it", "icons/file/audio.svg"),
    ("ixx", "icons/file/cpp.svg"),
    ("jav", "icons/file/java.svg"),
    ("java", "icons/file/java.svg"),
    ("jb2", "icons/file/image.svg"),
    ("jbig2", "icons/file/image.svg"),
    ("jfif", "icons/file/image.svg"),
    ("jl", "icons/file/julia.svg"),
    ("jmx", "icons/file/xml.svg"),
    ("jng", "icons/file/image.svg"),
    ("jpeg", "icons/file/image.svg"),
    ("jpg", "icons/file/image.svg"),
    ("jrxml", "icons/file/xml.svg"),
    ("js", "icons/file/javascript.svg"),
    ("jshtm", "icons/file/html.svg"),
    ("json", "icons/file/json.svg"),
    ("json5", "icons/file/json.svg"),
    ("jsonc", "icons/file/json.svg"),
    ("jsonl", "icons/file/json.svg"),
    ("jsonld", "icons/file/json.svg"),
    ("jsp", "icons/file/java.svg"),
    ("jsx", "icons/file/react.svg"),
    ("jxl", "icons/file/image.svg"),
    ("jxr", "icons/file/image.svg"),
    ("k25", "icons/file/image.svg"),
    ("kdbx", "icons/file/database.svg"),
    ("kdc", "icons/file/image.svg"),
    ("key", "icons/file/key.svg"),
    ("kra", "icons/file/image.svg"),
    ("ksh", "icons/file/console.svg"),
    ("kt", "icons/file/kotlin.svg"),
    ("kts", "icons/file/kotlin.svg"),
    ("ktx", "icons/file/image.svg"),
    ("ktx2", "icons/file/image.svg"),
    ("launch", "icons/file/xml.svg"),
    ("ldf", "icons/file/database.svg"),
    ("leex", "icons/file/elixir.svg"),
    ("less", "icons/file/less.svg"),
    ("lha", "icons/file/zip.svg"),
    ("lhs", "icons/file/haskell.svg"),
    ("litcoffee", "icons/file/markdown.svg"),
    ("liz", "icons/file/zip.svg"),
    ("lock", "icons/file/lock.svg"),
    ("lua", "icons/file/lua.svg"),
    ("lz", "icons/file/zip.svg"),
    ("lz4", "icons/file/zip.svg"),
    ("lz5", "icons/file/zip.svg"),
    ("lzh", "icons/file/zip.svg"),
    ("lzma", "icons/file/zip.svg"),
    ("lzma2", "icons/file/zip.svg"),
    ("m2v", "icons/file/video.svg"),
    ("m3u", "icons/file/audio.svg"),
    ("m3u8", "icons/file/audio.svg"),
    ("m4a", "icons/file/audio.svg"),
    ("m4b", "icons/file/audio.svg"),
    ("m4p", "icons/file/audio.svg"),
    ("m4r", "icons/file/audio.svg"),
    ("m4v", "icons/file/video.svg"),
    ("mak", "icons/file/settings.svg"),
    ("manifest", "icons/file/xml.svg"),
    ("markdn", "icons/file/markdown.svg"),
    ("markdown", "icons/file/markdown.svg"),
    ("mbox", "icons/file/email.svg"),
    ("md", "icons/file/markdown.svg"),
    ("mdb", "icons/file/database.svg"),
    ("mdc", "icons/file/image.svg"),
    ("mde", "icons/file/database.svg"),
    ("mdf", "icons/file/database.svg"),
    ("mdown", "icons/file/markdown.svg"),
    ("mdp", "icons/file/image.svg"),
    ("mdtext", "icons/file/markdown.svg"),
    ("mdtxt", "icons/file/markdown.svg"),
    ("mdwn", "icons/file/markdown.svg"),
    ("mdx", "icons/file/mdx.svg"),
    ("mef", "icons/file/image.svg"),
    ("menu", "icons/file/xml.svg"),
    ("mi", "icons/file/c.svg"),
    ("mid", "icons/file/audio.svg"),
    ("mii", "icons/file/cpp.svg"),
    ("mjs", "icons/file/javascript.svg"),
    ("mk", "icons/file/makefile.svg"),
    ("mka", "icons/file/audio.svg"),
    ("mkd", "icons/file/markdown.svg"),
    ("mkdn", "icons/file/markdown.svg"),
    ("mkv", "icons/file/video.svg"),
    ("mmf", "icons/file/audio.svg"),
    ("mod", "icons/file/audio.svg"),
    ("mos", "icons/file/image.svg"),
    ("mov", "icons/file/video.svg"),
    ("mp2", "icons/file/video.svg"),
    ("mp3", "icons/file/audio.svg"),
    ("mp4", "icons/file/video.svg"),
    ("mpc", "icons/file/audio.svg"),
    ("mpe", "icons/file/video.svg"),
    ("mpeg", "icons/file/video.svg"),
    ("mpg", "icons/file/video.svg"),
    ("mpv", "icons/file/video.svg"),
    ("mrf", "icons/file/font.svg"),
    ("mrw", "icons/file/image.svg"),
    ("mscz", "icons/file/audio.svg"),
    ("msg", "icons/file/email.svg"),
    ("msi", "icons/file/exe.svg"),
    ("mtm", "icons/file/audio.svg"),
    ("mts", "icons/file/typescript.svg"),
    ("mui", "icons/file/audio.svg"),
    ("musx", "icons/file/audio.svg"),
    ("mxl", "icons/file/audio.svg"),
    ("myd", "icons/file/database.svg"),
    ("myi", "icons/file/database.svg"),
    ("ndf", "icons/file/database.svg"),
    ("ndjson", "icons/file/json.svg"),
    ("nef", "icons/file/image.svg"),
    ("npmrc", "icons/file/settings.svg"),
    ("nrw", "icons/file/image.svg"),
    ("nsa", "icons/file/audio.svg"),
    ("ntf", "icons/file/font.svg"),
    ("ntfs", "icons/file/zip.svg"),
    ("nu", "icons/file/console.svg"),
    ("obm", "icons/file/image.svg"),
    ("odb", "icons/file/database.svg"),
    ("ods", "icons/file/table.svg"),
    ("odttf", "icons/file/font.svg"),
    ("oft", "icons/file/email.svg"),
    ("ogg", "icons/file/video.svg"),
    ("ogv", "icons/file/video.svg"),
    ("olm", "icons/file/email.svg"),
    ("opml", "icons/file/xml.svg"),
    ("option", "icons/file/settings.svg"),
    ("opus", "icons/file/audio.svg"),
    ("ora", "icons/file/image.svg"),
    ("orc", "icons/file/database.svg"),
    ("orf", "icons/file/image.svg"),
    ("ost", "icons/file/email.svg"),
    ("otf", "icons/file/font.svg"),
    ("owl", "icons/file/xml.svg"),
    ("p7s", "icons/file/email.svg"),
    ("pac", "icons/file/javascript.svg"),
    ("parquet", "icons/file/database.svg"),
    ("passwd", "icons/file/key.svg"),
    ("patch", "icons/file/git.svg"),
    ("pbm", "icons/file/image.svg"),
    ("pdb", "icons/file/database.svg"),
    ("pdf", "icons/file/pdf.svg"),
    ("pdn", "icons/file/image.svg"),
    ("pef", "icons/file/image.svg"),
    ("pem", "icons/file/key.svg"),
    ("pgf", "icons/file/image.svg"),
    ("pgm", "icons/file/image.svg"),
    ("pgsql", "icons/file/database.svg"),
    ("php", "icons/file/php.svg"),
    ("php4", "icons/file/php.svg"),
    ("php5", "icons/file/php.svg"),
    ("phtml", "icons/file/php.svg"),
    ("pic", "icons/file/image.svg"),
    ("pkb", "icons/file/database.svg"),
    ("pkf", "icons/file/audio.svg"),
    ("pks", "icons/file/database.svg"),
    ("plist", "icons/file/xml.svg"),
    ("plpgsql", "icons/file/database.svg"),
    ("pm", "icons/file/perl.svg"),
    ("png", "icons/file/image.svg"),
    ("pnm", "icons/file/image.svg"),
    ("pod", "icons/file/perl.svg"),
    ("podspec", "icons/file/ruby.svg"),
    ("postgres", "icons/file/database.svg"),
    ("ppm", "icons/file/image.svg"),
    ("prefs", "icons/file/settings.svg"),
    ("profile", "icons/file/console.svg"),
    ("proj", "icons/file/xml.svg"),
    ("project", "icons/file/xml.svg"),
    ("prop", "icons/file/settings.svg"),
    ("properties", "icons/file/settings.svg"),
    ("props", "icons/file/settings.svg"),
    ("ps1", "icons/file/powershell.svg"),
    ("ps1xml", "icons/file/powershell.svg"),
    ("psc1", "icons/file/powershell.svg"),
    ("psd1", "icons/file/powershell.svg"),
    ("psgi", "icons/file/perl.svg"),
    ("psm1", "icons/file/powershell.svg"),
    ("psql", "icons/file/database.svg"),
    ("psrc", "icons/file/powershell.svg"),
    ("pssc", "icons/file/powershell.svg"),
    ("pst", "icons/file/email.svg"),
    ("psv", "icons/file/table.svg"),
    ("ptx", "icons/file/image.svg"),
    ("pub", "icons/file/key.svg"),
    ("publishsettings", "icons/file/xml.svg"),
    ("pubxml", "icons/file/xml.svg"),
    ("pubxml.user", "icons/file/xml.svg"),
    ("pxn", "icons/file/image.svg"),
    ("py", "icons/file/python.svg"),
    ("pyi", "icons/file/python.svg"),
    ("pyt", "icons/file/python.svg"),
    ("pyw", "icons/file/python.svg"),
    ("qcp", "icons/file/audio.svg"),
    ("qt", "icons/file/video.svg"),
    ("r", "icons/file/r.svg"),
    ("r3d", "icons/file/image.svg"),
    ("ra", "icons/file/audio.svg"),
    ("raf", "icons/file/image.svg"),
    ("rake", "icons/file/ruby.svg"),
    ("raku", "icons/file/perl.svg"),
    ("rar", "icons/file/zip.svg"),
    ("raw", "icons/file/image.svg"),
    ("rb", "icons/file/ruby.svg"),
    ("rbi", "icons/file/ruby.svg"),
    ("rbs", "icons/file/ruby.svg"),
    ("rbx", "icons/file/ruby.svg"),
    ("rdf", "icons/file/xml.svg"),
    ("reb", "icons/file/image.svg"),
    ("repo", "icons/file/settings.svg"),
    ("resx", "icons/file/xml.svg"),
    ("rf64", "icons/file/audio.svg"),
    ("rhistory", "icons/file/r.svg"),
    ("rhtml", "icons/file/html.svg"),
    ("rip", "icons/file/audio.svg"),
    ("rjs", "icons/file/ruby.svg"),
    ("rm", "icons/file/video.svg"),
    ("rmd", "icons/file/r.svg"),
    ("rmvb", "icons/file/video.svg"),
    ("rng", "icons/file/xml.svg"),
    ("ron", "icons/file/rust.svg"),
    ("ronn", "icons/file/markdown.svg"),
    ("rpm", "icons/file/zip.svg"),
    ("rpmsg", "icons/file/email.svg"),
    ("rprofile", "icons/file/r.svg"),
    ("rpy", "icons/file/python.svg"),
    ("rs", "icons/file/rust.svg"),
    ("rss", "icons/file/xml.svg"),
    ("rst", "icons/file/markdown.svg"),
    ("rt", "icons/file/r.svg"),
    ("ru", "icons/file/ruby.svg"),
    ("rw2", "icons/file/image.svg"),
    ("rwl", "icons/file/image.svg"),
    ("rwz", "icons/file/image.svg"),
    ("sai", "icons/file/image.svg"),
    ("sass", "icons/file/sass.svg"),
    ("sc", "icons/file/scala.svg"),
    ("scala", "icons/file/scala.svg"),
    ("scss", "icons/file/sass.svg"),
    ("sdf", "icons/file/database.svg"),
    ("sdt", "icons/file/audio.svg"),
    ("secret", "icons/file/key.svg"),
    ("sesx", "icons/file/audio.svg"),
    ("settings", "icons/file/settings.svg"),
    ("sf2", "icons/file/audio.svg"),
    ("sh", "icons/file/console.svg"),
    ("sha256", "icons/file/key.svg"),
    ("sha256sum", "icons/file/key.svg"),
    ("sha256sums", "icons/file/key.svg"),
    ("shasum", "icons/file/key.svg"),
    ("shproj", "icons/file/xml.svg"),
    ("shtml", "icons/file/html.svg"),
    ("sln.dotsettings", "icons/file/settings.svg"),
    ("sln.dotsettings.user", "icons/file/settings.svg"),
    ("sql", "icons/file/database.svg"),
    ("sqlite", "icons/file/database.svg"),
    ("sqlite3", "icons/file/database.svg"),
    ("squashfs", "icons/file/zip.svg"),
    ("sr2", "icons/file/image.svg"),
    ("srf", "icons/file/image.svg"),
    ("srw", "icons/file/image.svg"),
    ("stap", "icons/file/audio.svg"),
    ("storyboard", "icons/file/xml.svg"),
    ("sui", "icons/file/font.svg"),
    ("suit", "icons/file/font.svg"),
    ("svelte", "icons/file/svelte.svg"),
    ("svg", "icons/file/svg.svg"),
    ("swift", "icons/file/swift.svg"),
    ("swiftdeps", "icons/file/swift.svg"),
    ("swiftdoc", "icons/file/swift.svg"),
    ("swiftmodule", "icons/file/swift.svg"),
    ("swiftsourceinfo", "icons/file/swift.svg"),
    ("swm", "icons/file/zip.svg"),
    ("t", "icons/file/perl.svg"),
    ("tar", "icons/file/zip.svg"),
    ("targets", "icons/file/xml.svg"),
    ("taz", "icons/file/zip.svg"),
    ("tbz", "icons/file/zip.svg"),
    ("tbz2", "icons/file/zip.svg"),
    ("tcc", "icons/file/hpp.svg"),
    ("tcsh", "icons/file/console.svg"),
    ("tcshrc", "icons/file/console.svg"),
    ("terraformignore", "icons/file/terraform.svg"),
    ("tf", "icons/file/terraform.svg"),
    ("tf.json", "icons/file/terraform.svg"),
    ("tfbackend", "icons/file/terraform.svg"),
    ("tfstate", "icons/file/terraform.svg"),
    ("tfvars", "icons/file/terraform.svg"),
    ("tg", "icons/file/audio.svg"),
    ("tga", "icons/file/image.svg"),
    ("tgz", "icons/file/zip.svg"),
    ("tif", "icons/file/image.svg"),
    ("tiff", "icons/file/image.svg"),
    ("tld", "icons/file/xml.svg"),
    ("tlz", "icons/file/zip.svg"),
    ("tmlanguage", "icons/file/xml.svg"),
    ("tmx", "icons/file/xml.svg"),
    ("tnef", "icons/file/email.svg"),
    ("todo", "icons/file/todo.svg"),
    ("toml", "icons/file/toml.svg"),
    ("tool-versions", "icons/file/settings.svg"),
    ("tpp", "icons/file/cpp.svg"),
    ("tpz", "icons/file/zip.svg"),
    ("ts", "icons/file/typescript.svg"),
    ("ts.map", "icons/file/json.svg"),
    ("tsbuildinfo", "icons/file/json.svg"),
    ("tsv", "icons/file/table.svg"),
    ("tsx", "icons/file/react_ts.svg"),
    ("ttc", "icons/file/font.svg"),
    ("ttf", "icons/file/font.svg"),
    ("txt", "icons/file/document.svg"),
    ("txx", "icons/file/cpp.svg"),
    ("txz", "icons/file/zip.svg"),
    ("tz", "icons/file/zip.svg"),
    ("tzst", "icons/file/zip.svg"),
    ("tzstd", "icons/file/zip.svg"),
    ("vbproj", "icons/file/xml.svg"),
    ("vbproj.user", "icons/file/xml.svg"),
    ("vob", "icons/file/video.svg"),
    ("voc", "icons/file/audio.svg"),
    ("volt", "icons/file/html.svg"),
    ("vqf", "icons/file/audio.svg"),
    ("vue", "icons/file/vue.svg"),
    ("wav", "icons/file/audio.svg"),
    ("weba", "icons/file/audio.svg"),
    ("webm", "icons/file/video.svg"),
    ("webmanifest", "icons/file/json.svg"),
    ("webp", "icons/file/image.svg"),
    ("wfp", "icons/file/audio.svg"),
    ("wim", "icons/file/zip.svg"),
    ("winget", "icons/file/yaml.svg"),
    ("wma", "icons/file/audio.svg"),
    ("wmv", "icons/file/video.svg"),
    ("woff", "icons/file/font.svg"),
    ("woff2", "icons/file/font.svg"),
    ("workbook", "icons/file/markdown.svg"),
    ("wpl", "icons/file/audio.svg"),
    ("wproj", "icons/file/audio.svg"),
    ("wsdl", "icons/file/xml.svg"),
    ("wv", "icons/file/audio.svg"),
    ("wxi", "icons/file/xml.svg"),
    ("wxl", "icons/file/xml.svg"),
    ("wxs", "icons/file/xml.svg"),
    ("x3f", "icons/file/image.svg"),
    ("xar", "icons/file/zip.svg"),
    ("xbl", "icons/file/xml.svg"),
    ("xcf", "icons/file/image.svg"),
    ("xcplayground", "icons/file/swift.svg"),
    ("xht", "icons/file/html.svg"),
    ("xhtml", "icons/file/html.svg"),
    ("xib", "icons/file/xml.svg"),
    ("xliff", "icons/file/xml.svg"),
    ("xls", "icons/file/table.svg"),
    ("xlsm", "icons/file/table.svg"),
    ("xlsx", "icons/file/table.svg"),
    ("xml", "icons/file/xml.svg"),
    ("xml.dist", "icons/file/xml.svg"),
    ("xml.dist.sample", "icons/file/xml.svg"),
    ("xmp", "icons/file/xml.svg"),
    ("xoml", "icons/file/xml.svg"),
    ("xpdl", "icons/file/xml.svg"),
    ("xprofile", "icons/file/console.svg"),
    ("xquery", "icons/file/xml.svg"),
    ("xsd", "icons/file/xml.svg"),
    ("xsession", "icons/file/console.svg"),
    ("xsessionrc", "icons/file/console.svg"),
    ("xsh", "icons/file/console.svg"),
    ("xsl", "icons/file/xml.svg"),
    ("xslt", "icons/file/xml.svg"),
    ("xul", "icons/file/xml.svg"),
    ("xz", "icons/file/zip.svg"),
    ("yaml", "icons/file/yaml.svg"),
    ("yaml-tmlanguage", "icons/file/yaml.svg"),
    ("yaml-tmpreferences", "icons/file/yaml.svg"),
    ("yaml-tmtheme", "icons/file/yaml.svg"),
    ("yaml.dist", "icons/file/yaml.svg"),
    ("yash_profile", "icons/file/console.svg"),
    ("yashrc", "icons/file/console.svg"),
    ("yml", "icons/file/yaml.svg"),
    ("yml.dist", "icons/file/yaml.svg"),
    ("yuv", "icons/file/video.svg"),
    ("z", "icons/file/zip.svg"),
    ("zig", "icons/file/zig.svg"),
    ("zip", "icons/file/zip.svg"),
    ("zlogin", "icons/file/console.svg"),
    ("zlogout", "icons/file/console.svg"),
    ("zon", "icons/file/zig.svg"),
    ("zprofile", "icons/file/console.svg"),
    ("zsh", "icons/file/console.svg"),
    ("zsh-theme", "icons/file/console.svg"),
    ("zshenv", "icons/file/console.svg"),
    ("zshrc", "icons/file/console.svg"),
    ("zst", "icons/file/zip.svg"),
    ("zstd", "icons/file/zip.svg"),
];

pub(crate) static FOLDER_NAMES: &[(&str, &str, &str)] = &[
    (".api", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    (".apis", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    (".app", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    (".application", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    (".applications", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    (".apps", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    (".article", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".articles", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".asset", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".assets", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".bench", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".benches", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".benchmark", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".benchmarks", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".bin", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".blog", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".browser", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".browsers", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".build", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".builds", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".built", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".cache", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    (".cached", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    (".cargo", "icons/file/folder-rust.svg", "icons/file/folder-rust-open.svg"),
    (".cfg", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".cfgs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".code", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    (".compiled", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".components", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    (".conf", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".config", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".configs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".configuration", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".configurations", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".confs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".core", "icons/file/folder-core.svg", "icons/file/folder-core-open.svg"),
    (".crates", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".data", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    (".database", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    (".databases", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    (".db", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    (".demo", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".demos", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".dependencies", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".devpackages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".devtools", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".diary", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".dist", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".distribution", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".doc", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".docs", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".document", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".documentation", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".documents", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".example", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".examples", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".external", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".externals", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".fig", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".figs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".figure", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".figures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".fragments", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    (".git", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    (".githooks", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    (".github", "icons/file/folder-github.svg", "icons/file/folder-github-open.svg"),
    (".hook", "icons/file/folder-hook.svg", "icons/file/folder-hook-open.svg"),
    (".hooks", "icons/file/folder-hook.svg", "icons/file/folder-hook-open.svg"),
    (".ico", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".icon", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".icons", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".icos", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".image", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".images", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".img", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".imgs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".kit", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".kits", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".knowledge", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".lib", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".lib64", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".libraries", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".library", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".libs", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".measure", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".measurement", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".measures", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".meta-inf", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".news", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".node", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    (".node_modules", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    (".nodejs", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    (".note", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".notes", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".option", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".options", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".out", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".output", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".outputs", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".package", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".packages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".patches", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    (".perf", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".performance", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".photo", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".photograph", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".photographs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".photos", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".pic", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".pics", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".picture", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".pictures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".pkg", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".pkgs", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".post", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".posts", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".pref", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".preference", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".preferences", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".prefs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".profiling", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    (".properties", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".props", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".proxy", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".public", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".release", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    (".report", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".reports", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".res", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".resource", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".resources", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".restapi", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    (".rust", "icons/file/folder-rust.svg", "icons/file/folder-rust-open.svg"),
    (".sample", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".sample-data", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".samples", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    (".screengrab", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".screengrabs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".screenshot", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".screenshots", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".script", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    (".scripting", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    (".scripts", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    (".serverpackages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    (".setting", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".settings", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    (".site", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".snapshots", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".source", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    (".sources", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    (".spec", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".specs", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".sql", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    (".src", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    (".srcs", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    (".static", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    (".submodules", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    (".target", "icons/file/folder-target.svg", "icons/file/folder-target-open.svg"),
    (".temp", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    (".test", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".testfiles", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".testing", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".tests", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    (".texture", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".textures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    (".third-party", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".thirdparty", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".tmp", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    (".toolbox", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".toolboxes", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".tooling", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".toolkit", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".toolkits", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".tools", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    (".util", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    (".utilities", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    (".utility", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    (".utils", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    (".vendor", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".vendors", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    (".vscode", "icons/file/folder-vscode.svg", "icons/file/folder-vscode-open.svg"),
    (".vscode-test", "icons/file/folder-vscode.svg", "icons/file/folder-vscode-open.svg"),
    (".web", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".website", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".websites", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".widget", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    (".widgets", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    (".wiki", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    (".www", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".wwwroot", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    (".xtask", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    ("api", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    ("apis", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    ("app", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    ("application", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    ("applications", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    ("apps", "icons/file/folder-app.svg", "icons/file/folder-app-open.svg"),
    ("article", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("articles", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("asset", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("assets", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("bench", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("benches", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("benchmark", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("benchmarks", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("bin", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("blog", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("browser", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("browsers", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("build", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("builds", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("built", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("cache", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    ("cached", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    ("cargo", "icons/file/folder-rust.svg", "icons/file/folder-rust-open.svg"),
    ("cfg", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("cfgs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("code", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    ("compiled", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("components", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    ("conf", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("config", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("configs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("configuration", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("configurations", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("confs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("core", "icons/file/folder-core.svg", "icons/file/folder-core-open.svg"),
    ("crates", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("data", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    ("database", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    ("databases", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    ("db", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    ("demo", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("demos", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("dependencies", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("devpackages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("devtools", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("diary", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("dist", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("distribution", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("doc", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("docs", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("document", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("documentation", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("documents", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("example", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("examples", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("external", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("externals", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("fig", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("figs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("figure", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("figures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("fragments", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    ("git", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    ("githooks", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    ("github", "icons/file/folder-github.svg", "icons/file/folder-github-open.svg"),
    ("hook", "icons/file/folder-hook.svg", "icons/file/folder-hook-open.svg"),
    ("hooks", "icons/file/folder-hook.svg", "icons/file/folder-hook-open.svg"),
    ("ico", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("icon", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("icons", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("icos", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("image", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("images", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("img", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("imgs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("kit", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("kits", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("knowledge", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("lib", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("lib64", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("libraries", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("library", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("libs", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("measure", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("measurement", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("measures", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("meta-inf", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("news", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("node", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    ("node_modules", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    ("nodejs", "icons/file/folder-node.svg", "icons/file/folder-node-open.svg"),
    ("note", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("notes", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("option", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("options", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("out", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("output", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("outputs", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("package", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("packages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("patches", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    ("perf", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("performance", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("photo", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("photograph", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("photographs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("photos", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("pic", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("pics", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("picture", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("pictures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("pkg", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("pkgs", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("post", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("posts", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("pref", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("preference", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("preferences", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("prefs", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("profiling", "icons/file/folder-benchmark.svg", "icons/file/folder-benchmark-open.svg"),
    ("properties", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("props", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("proxy", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("public", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("release", "icons/file/folder-dist.svg", "icons/file/folder-dist-open.svg"),
    ("report", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("reports", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("res", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("resource", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("resources", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("restapi", "icons/file/folder-api.svg", "icons/file/folder-api-open.svg"),
    ("rust", "icons/file/folder-rust.svg", "icons/file/folder-rust-open.svg"),
    ("sample", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("sample-data", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("samples", "icons/file/folder-examples.svg", "icons/file/folder-examples-open.svg"),
    ("screengrab", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("screengrabs", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("screenshot", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("screenshots", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("script", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    ("scripting", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    ("scripts", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
    ("serverpackages", "icons/file/folder-packages.svg", "icons/file/folder-packages-open.svg"),
    ("setting", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("settings", "icons/file/folder-config.svg", "icons/file/folder-config-open.svg"),
    ("site", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("snapshots", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("source", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    ("sources", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    ("spec", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("specs", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("sql", "icons/file/folder-database.svg", "icons/file/folder-database-open.svg"),
    ("src", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    ("srcs", "icons/file/folder-src.svg", "icons/file/folder-src-open.svg"),
    ("static", "icons/file/folder-resource.svg", "icons/file/folder-resource-open.svg"),
    ("submodules", "icons/file/folder-git.svg", "icons/file/folder-git-open.svg"),
    ("target", "icons/file/folder-target.svg", "icons/file/folder-target-open.svg"),
    ("temp", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    ("test", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("testfiles", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("testing", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("tests", "icons/file/folder-test.svg", "icons/file/folder-test-open.svg"),
    ("texture", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("textures", "icons/file/folder-images.svg", "icons/file/folder-images-open.svg"),
    ("third-party", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("thirdparty", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("tmp", "icons/file/folder-temp.svg", "icons/file/folder-temp-open.svg"),
    ("toolbox", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("toolboxes", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("tooling", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("toolkit", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("toolkits", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("tools", "icons/file/folder-tools.svg", "icons/file/folder-tools-open.svg"),
    ("util", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    ("utilities", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    ("utility", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    ("utils", "icons/file/folder-utils.svg", "icons/file/folder-utils-open.svg"),
    ("vendor", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("vendors", "icons/file/folder-lib.svg", "icons/file/folder-lib-open.svg"),
    ("vscode", "icons/file/folder-vscode.svg", "icons/file/folder-vscode-open.svg"),
    ("vscode-test", "icons/file/folder-vscode.svg", "icons/file/folder-vscode-open.svg"),
    ("web", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("website", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("websites", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("widget", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    ("widgets", "icons/file/folder-components.svg", "icons/file/folder-components-open.svg"),
    ("wiki", "icons/file/folder-docs.svg", "icons/file/folder-docs-open.svg"),
    ("www", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("wwwroot", "icons/file/folder-public.svg", "icons/file/folder-public-open.svg"),
    ("xtask", "icons/file/folder-scripts.svg", "icons/file/folder-scripts-open.svg"),
];
